### ISSUE TITLE
3080ti (12 G) can't run it?

### ISSUE THREAD

**Issue by jiaozn** [LC1332/Chinese-alpaca-lora#10]
python app.py --base_url llama7b --ft_ckpt_url luotuolora7b03 --port 6006 --share yes

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: Required library version not found: libsbitsandbytes_cpu.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes_cpu.so...
argument of type 'WindowsPath' is not iterable
D:\ProgramData\Anaconda3\envs\chinese_luotuo3\lib\site-packages\bitsandbytes\cextension.py:31: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization.
The tokenizer class you load from this checkpoint is 'LLaMATokenizer'.
The class this function is called from is 'LlamaTokenizer'.
Overriding torch_dtype=None with `torch_dtype=torch.float16` due to requirements of `bitsandbytes` to enable model loading in mixed int8. Either pass torch_dtype=torch.float16 or don't pass this argument at all to remove this warning.
Traceback (most recent call last):
  File "D:\chinese_alpaca_lora\Chinese-alpaca-lora\notebook\Alpaca-LoRA-Serve\app.py", line 178, in <module>
    run(args)
  File "D:\chinese_alpaca_lora\Chinese-alpaca-lora\notebook\Alpaca-LoRA-Serve\app.py", line 79, in run
    model, tokenizer = load_model(
  File "D:\chinese_alpaca_lora\Chinese-alpaca-lora\notebook\Alpaca-LoRA-Serve\model.py", line 12, in load_model
    model = LlamaForCausalLM.from_pretrained(
  File "D:\ProgramData\Anaconda3\envs\chinese_luotuo3\lib\site-packages\transformers\modeling_utils.py", line 2588, in from_pretrained
    raise ValueError(
ValueError:
                        Some modules are dispatched on the CPU or the disk. Make sure you have enough GPU RAM to fit
                        the quantized model. If you want to dispatch the model on the CPU or the disk while keeping
                        these modules in 32-bit, you need to set `load_in_8bit_fp32_cpu_offload=True` and pass a custom
                        `device_map` to `from_pretrained`. Check
                        https://huggingface.co/docs/transformers/main/en/main_classes/quantization#offload-between-cpu-and-gpu
                        for more details.

---------------------------
win10 + 3080ti
I type in command and get these...it seems my GPU RAM (12 G) is not enough for it?

![image](https://user-images.githubusercontent.com/12379029/227531423-2daf8e97-cc34-4c19-beb8-181f5c0e5224.png)

**Comment by qiyuan-chen** [comment]
Thank you for your interest and testing. First of all, 3080ti is sufficient for model inference and we have been able to run the inference code successfully on colab's k80. Secondly, your problem is an error in the runtime environment, bitsandbytes does not recognize your GPU, it may be that the environment such as bitsandbytes or cuda is not properly configured, we suggest to try to reconfigure the runtime environment.

**Comment by jiaozn** [comment]
> > Thank you for your interest and testing. First of all, 3080ti is sufficient for model inference and we have been able to run the inference code successfully on colab's k80. Secondly, your problem is an error in the runtime environment, bitsandbytes does not recognize your GPU, it may be that the environment such as bitsandbytes or cuda is not properly configured, we suggest to try to reconfigure the runtime environment.
> 
> Thanks! I think i got the answer. you're right, the answer is Windows
> 
> ![image](https://user-images.githubusercontent.com/12379029/227539638-9a744a6a-2cb5-4bed-9427-09962cc7a2d8.png) ——https://github.com/TimDettmers/bitsandbytes




That's it! It's OK with linux~~
![2023-03-25 00-15-14 的屏幕截图](https://user-images.githubusercontent.com/12379029/227582199-15131ff3-28eb-49a6-9578-f60bcfd47ffa.png)
