### ISSUE TITLE
AutoTokenizer problem

### ISSUE THREAD

**Issue by yangzhipeng1108** [LC1332/Chinese-alpaca-lora#13]
Unrecognized configuration class <class 'transformers_modules.local.configuration_chatglm.ChatGLMConfig'> to build an AutoTokenizer.

**Comment by qiyuan-chen** [comment]
感谢您的关注。我不知道您说的是哪一个文件的问题，但我感觉这个可能是您transformers包的版本问题，请尝试安装4.26.1版本的transformers，若有问题可以继续comment

**Comment by yangzhipeng1108** [comment]
problem solving

**Comment by qiyuan-chen** [comment]
Have you solved your problem? if yes, please close the comment
