### ISSUE TITLE
llama的原生词表基本没有中文，是用的200多个UTF-8码的组合来表示中文的。

### ISSUE THREAD

**Issue by Porraio** [LC1332/Chinese-alpaca-lora#18]
llama原生模型是没有经过中文预训练的，词表也基本没中文，直接fine-tune是不是效果没法保障。你们有试过扩展词表吗。谢谢回答。

**Comment by qiyuan-chen** [comment]
感谢您的提问与测试。我们目前已经发现了llama的tokenizer效果很差，正在进一步研究，同时我们也在尝试将基模型换成其他的（e.g. GLM）进行更多的尝试。由于我们人比较少，所以工作做的比较慢，还烦请您进一步关注。

**Comment by LC1332** [comment]
对的，我们想训练一个和llama原生能长度匹配的tokenizer，然后一下子input进去去观测finetune的行为。不过这里面需要把特殊的几个token都仔细对齐。

**Comment by Porraio** [comment]
> 对的，我们想训练一个和llama原生能长度匹配的tokenizer，然后一下子input进去去观测finetune的行为。不过这里面需要把特殊的几个token都仔细对齐。

改了tokenizer后，原本的权重也没有对应token的embedding，只能扩展然后随机初始化吧。。

**Comment by qiyuan-chen** [comment]
是这样的，我觉得你说的没错，其实我个人也觉得这样的作法可能难度较大，如果有时间可以留下您的联系方式，我们聊聊您的思路？

**Comment by LC1332** [comment]
> > 对的，我们想训练一个和llama原生能长度匹配的tokenizer，然后一下子input进去去观测finetune的行为。不过这里面需要把特殊的几个token都仔细对齐。
> 
> 改了tokenizer后，原本的权重也没有对应token的embedding，只能扩展然后随机初始化吧。。

我想了一些简易的办法，不过开发这部分还挺花时间的，但是我觉得这是个很有意义的事情，我会把这个放到骆驼1.0以后的开发计划中。
