### ISSUE TITLE
problem in adapter_config.json loading to finetune

### ISSUE THREAD

**Issue by JackYang-Giihub** [LC1332/Chinese-alpaca-lora#19]
ValueError: Unrecognized model in [./model/adapter_config.json.] (Chinese-alpaca-lora/model/adapter_config.json.) Should have a `model_type` key in its config.json, or contain one of the following strings in its name:..

Model type is not metioned in adapter_config.json. 
Should I fill model type 'llama'? But llama is not transformers structures

best regards.

**Comment by qiyuan-chen** [comment]
It is not necessary to download the model from huggingface and then test it, you can use it directly during the run, this method should not report an error, please try this method
