### ISSUE TITLE
对于code的总结和生成是否有进行微调

### ISSUE THREAD

**Issue by Tavish77** [LC1332/Chinese-alpaca-lora#2]
使用llama_index，总结我的代码文档时候，效果极差，甚至不会说话，想问问是否确实没有对这方面进行finetune

**Comment by LC1332** [comment]
@Tavish77 这个还没有时间去做，如果您有兴趣可以加入了做，据我所知用lLAMA65B来做code生成的时候效果很好。

**Comment by Tavish77** [comment]
@LC1332 多谢 我去看看
