### ISSUE TITLE
有进行模型效果评测吗？

### ISSUE THREAD

**Issue by Syno8** [LC1332/Chinese-alpaca-lora#2]
除了readme 上的一些examples 对比，有没有在各方面能力上的对比？

**Comment by LC1332** [comment]
我后面是准备做的，做完会写一个技术总结报告挂到arxiv，如果有建议也可以发给我哈～～

**Comment by Syno8** [comment]
@LC1332 像这种模型的做法，还能在NLP task 上取得比较好的效果吗？例如文本分类之类的任务？

**Comment by LC1332** [comment]
> @LC1332 像这种模型的做法，还能在NLP task 上取得比较好的效果吗？例如文本分类之类的任务？

我们下周或者下下周会有更新，会去做这种下游任务。你要不等一等？
