### ISSUE TITLE
!pip install -q git+https://github.com/zphang/transformers@c3dc391

### ISSUE THREAD

**Issue by lelegogo26** [LC1332/Chinese-alpaca-lora#20]
这个没法安装，怎么解决

**Comment by felicity1225** [comment]
reinstall transformers
pip uninstall transformers 
pip install git+https://github.com/huggingface/transformers.git

**Comment by qiyuan-chen** [comment]
感谢二位的关注也感谢 @felicity1225 的回答，这样的作法我们还没尝试过，是有效的吗？

**Comment by felicity1225** [comment]
嗯，可以的，llama模型和分词已经加到main里了，import的时候大小写改下，from transformers import LlamaForCausalLM, LlamaTokenizer

**Comment by qiyuan-chen** [comment]
感谢回复，我们会更新到evaluate的代码当中~

**Comment by songtaoshi** [comment]
我就是按照上面的操作更改了，但是decode example出来下面的情况，会和这个tokenization有关吗？？    
Instruction: 猫和狗的关系是什么
Response: ��和狗的关系是很好的。��和��的关系是很好的，他们可以共享生活，共享家��，共享食，共����������������������������������人人人人人人人人人人人人人人人人人人人人人人人人人人人人人人人人人人人人人人人人人人人人人人人人人人人人人人��

@felicity1225 @qiyuan-chen
