### ISSUE TITLE
CUDA SETUP: WARNING! libcuda.so not found!

### ISSUE THREAD

**Issue by forrestneo** [LC1332/Chinese-alpaca-lora#23]
`/home/zsd/.local/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('qychen/luotuo-lora-7b-0.1')}
  warn(msg)
/home/zsd/.local/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('unix')}
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
/home/zsd/.local/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: No GPU detected! Check your CUDA paths. Proceeding to load CPU-only library...
  warn(msg)
CUDA SETUP: Loading binary /home/zsd/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so...
/home/zsd/.local/lib/python3.10/site-packages/bitsandbytes/cextension.py:31: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers and GPU quantization are unavailable....
    from model import load_model  File "/home/zsd/Chinese-alpaca-lora/notebook/Alpaca-LoRA-Serve/model.py", line 2, in <module>
    from transformers import LlamaTokenizer, LlamaForCausalLM
ImportError: cannot import name 'LlamaTokenizer' from 'transformers' (/home/zsd/anaconda3/lib/python3.10/site-packages/transformers/__init__.py)
`

**Comment by MrToy** [comment]
pip install git+https://github.com/huggingface/transformers.git

**Comment by qiyuan-chen** [comment]
Thank you for your attention and testing. Our model can currently only be tested on machines with GPUs. It seems that your machine does not have GPU support or CUDA is not installed correctly. Please check your environment again to ensure that it is correct.
