### ISSUE TITLE
基于中文pretrain的模型是否效果会更好

### ISSUE THREAD

**Issue by MrToy** [LC1332/Chinese-alpaca-lora#24]
在隔壁看到了https://github.com/ymcui/Chinese-LLaMA-Alpaca 这样的项目
先在llama上使用中文数据集做了pretrain，然后再使用alpaca进行的微调
对比了下glm-6b和llama-7b-zh，感觉llama更擅长instruction任务一些

**Comment by BlairLeng** [comment]
会，这个项目我们也关注了，我们也这么想了，打算试一下！

**Comment by BlairLeng** [comment]
@MrToy
