### ISSUE TITLE
RetryError[<Future at 0x7fb1a0073b50 state=finished raised TypeError>]

### ISSUE THREAD

**Issue by firstboost** [LC1332/Chinese-alpaca-lora#25]
when I ask something,server having error:

RetryError[<Future at 0x7fb1a0073b50 state=finished raised TypeError>]

![1680155524941](https://user-images.githubusercontent.com/129361859/228741975-608b7b40-0402-41b1-afcb-e0ba99238645.png)

logs:

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
/root/anaconda3/envs/luotuo/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: /root/anaconda3/envs/luotuo did not contain libcudart.so as expected! Searching further paths...
  warn(msg)
CUDA SETUP: CUDA runtime path found: /usr/local/cuda-11.0/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 3.7
CUDA SETUP: Detected CUDA version 110
/root/anaconda3/envs/luotuo/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: Compute capability < 7.5 detected! Only slow 8-bit matmul is supported for your GPU!
  warn(msg)
CUDA SETUP: Loading binary /root/anaconda3/envs/luotuo/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda110_nocublaslt.so...
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'LLaMATokenizer'. 
The class this function is called from is 'LlamaTokenizer'.
Overriding torch_dtype=None with `torch_dtype=torch.float16` due to requirements of `bitsandbytes` to enable model loading in mixed int8. Either pass torch_dtype=torch.float16 or don't pass this argument at all to remove this warning.
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 33/33 [00:20<00:00,  1.63it/s]
Running on local URL:  http://0.0.0.0:6006
Running on public URL: https://cb229e153757d1c9cd.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades (NEW!), check out Spaces: https://huggingface.co/spaces
RetryError[<Future at 0x7fb1a0319f90 state=finished raised TypeError>]

**Comment by qiyuan-chen** [comment]
Thank you for your attention and testing. There are currently some bugs in our web-based code, and we cannot guarantee that it will produce the same results as the notebook. However, we are working to resolve the issue. Please use the notebook to experience our model for the time being.

**Comment by firstboost** [comment]
ok,thanks.
