### ISSUE TITLE
这个是数据集太固定了吗

### ISSUE THREAD

**Issue by jinfagang** [LC1332/Chinese-alpaca-lora#4]
![image](https://user-images.githubusercontent.com/21303438/227089526-b0e3501e-5f7d-4f6d-b4a7-04b8af6c7409.png)

**Comment by LC1332** [comment]
目前ChatLuotuo的代码和evaluate有区别，我还没有修复，另外大哥可以等一等我们的0.3模型，会有更多提升。另外连续对话我还没有空去提升，需要额外有一个模型。
