### ISSUE TITLE
failed to install lib...evaluation_code_0_3.ipynb

### ISSUE THREAD

**Issue by jiaozn** [LC1332/Chinese-alpaca-lora#5]
win10 + anaconda prompt
I use pip to install the libs,I got this...

--------------
C:\Users\j>pip install -q datasets loralib sentencepiece
  ERROR: Error [WinError 225] 无法成功完成操作，因为文件包含病毒或潜在的垃圾软件。 while executing command python setup.py egg_info
ERROR: Could not install packages due to an OSError: [WinError 225] 无法成功完成操作，因为文件包含病毒或潜在的垃圾软件。

**Comment by qiyuan-chen** [comment]
感谢您的关注。这个可能由于微软官方杀毒软件or其余杀毒软件的误报造成的，可以尝试在Windows安全中心中关闭相关设置来尝试解决

**Comment by jiaozn** [comment]
> 感谢您的关注。这个可能由于微软官方杀毒软件or其余杀毒软件的误报造成的，可以尝试在Windows安全中心中关闭相关设置来尝试解决

Thx!
Done!
![image](https://user-images.githubusercontent.com/12379029/227176644-5cb4bc30-4889-4f2c-b6f1-a189adc5a35e.png)

**Comment by qiyuan-chen** [comment]
Nice！试用后还麻烦多多反馈，您的建议对我们很重要

**Comment by jiaozn** [comment]
> Nice！试用后还麻烦多多反馈，您的建议对我们很重要



> Nice！试用后还麻烦多多反馈，您的建议对我们很重要

by the way...
I failed to install sentencepiece With Python3.11 and it's OK when i use Python3.10
maybe because there's not suitable sentencepiece package for Python3.11 according to [this](https://github.com/google/sentencepiece/releases/tag/v0.1.97)-2023.3.23
