### ISSUE TITLE
What is the foundation model of Luotuo?

### ISSUE THREAD

**Issue by Nietism** [LC1332/Chinese-alpaca-lora#6]
I am sorry if i have not noticed. I am just curious about it. 
Are these models based on LLaMA, Alpaca or ChatGLM? The model definition and configuration of ChatGLM are in the `./PythonFiles` folder of this repository.

**Comment by BlairLeng** [comment]
Im sorry for confusion. Luotuo-0.1 and Luotuo-0.3 will be trained based on LLAMA. But we are trying to working on some new methods which using ChatGLM as base model. The README will be updated soon. Thank you for your like! @Nietism

**Comment by LC1332** [comment]
I know you question. The Luotuo was trained based on LLaMA, which traind trans-lingual, quite interesting in research. But if you are seeking a better Chinese performance, we should low rank adapt on  a Chinese based model instead of an English one.
