### ISSUE TITLE
需要啥样的硬件配置

### ISSUE THREAD

**Issue by harrychat** [LC1332/Chinese-alpaca-lora#7]
请问用的是啥GPU，V100可以跑吗？

**Comment by whynothackme** [comment]
V100肯定可以，我看colab消耗大概是>8G

**Comment by cjia4** [comment]
Collab上Tesla T4也可以跑。
用的是https://colab.research.google.com/github/LC1332/Chinese-alpaca-lora/blob/main/notebook/ChatLuotuo.ipynb

**Comment by whynothackme** [comment]
FINETUNED_CKPT_URL=qychen/luotuo-lora-7b-0.1 改成 %env FINETUNED_CKPT_URL=silk-road/luotuo-lora-7b-0.3
可以使用0.3的版本，感觉中文还是不太行，得用一些好的语料训练

**Comment by qiyuan-chen** [comment]
感谢以上所有朋友的关注与测试。我们的项目在evaluate阶段是可以在colab上测试的，v100是可以满足推理需求的。后续在我们训练代码放出后，我们也会测试更加详细的硬件配置要求。另外，luotuo还是一个非常粗浅的尝试，我们的显卡也非常不足，所以用大规模语料训练的速度会比较慢，因此0.3版本只是在更大规模语料上训练一个epoch后的结果。我们会保持更新，如果可以的话请持续关注与测试！

**Comment by lindeer** [comment]
@qiyuan-chen 训练出的模型可以跑在alpaca.cpp项目上吗，我试了下读取模型失败，很多人像我一样，机器没有GPU要，也想体验一下 :pray:

**Comment by yi** [comment]
alpaca.cpp 走CPU计算，非常非常的慢。如果只是使用模型而不是训练模型的话，Nvidia 的矿渣卡很合适，比如 cmp 40hx, 50hx

**Comment by lindeer** [comment]
@yi 谢谢，就想看看模型能不能运行，但是加载报错，不知要怎么转换下格式
