### ISSUE TITLE
训练数据中的引号问题

### ISSUE THREAD

**Issue by wjfwzzc** [LC1332/Chinese-alpaca-lora#8]
训练数据中对引号的使用似乎有一些错乱？诸如

1. 整个字段被中文或英文引号包围
2. 字段中的英文引号部分没有转译成中文引号
3. 倘若字段被双引号包围，则字段内的双引号被改写成了单引号

这些现象会对模型的效果产生影响么？

**Comment by qiyuan-chen** [comment]
感谢您的关注以及对数据集的详细观察。这个问题我们在0.1的训练前已经关注到了，但是我们当时为了尽快能推出第一版的模型，所以对数据并没有做太多的清理，但我们已在后续的工作中做了数据的清理同时添加了更多的语料，后续也会放出更加干净和丰富的数据。如果您感兴趣，可以持续关注我们的github。最后，再次感谢您的关注与建议。
