### ISSUE TITLE
from transformers import LLaMATokenizer, LLaMAForCausalLM 报错如何解决

### ISSUE THREAD

**Issue by dizhi916** [LC1332/Chinese-alpaca-lora#9]
pip install transformers 后，from transformers import LLaMATokenizer, LLaMAForCausalLM 报错，为什么，或者哪里错了？

**Comment by qiyuan-chen** [comment]
感谢您的关注与测试。需要注意的是请不要直接使用pip install transformers，因为原来的transformers并不包含这些函数。请按照我们evaluate的中的装包过程进行环境配置。如果有问题可以继续反馈，感谢！

**Comment by wangweiweinimeng** [comment]
遇到类似的问题，执行!pip install -q git+https://github.com/zphang/transformers@c3dc391，报错如下：
Looking in indexes: https://mirrors.aliyun.com/pypi/simple
Requirement already satisfied: bitsandbytes in /usr/local/lib/python3.6/dist-packages (0.37.2)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
  ERROR: Command errored out with exit status 128:
   command: git clone --filter=blob:none -q https://github.com/zphang/transformers /tmp/pip-req-build-6duc7ssd
       cwd: None
  Complete output (1 lines):
  fatal: unable to access 'https://github.com/zphang/transformers/': gnutls_handshake() failed: The TLS connection was non-properly terminated.
  ----------------------------------------
访问https://github.com/zphang/transformers显示这个repo已经迁移到另一个repo地址了
请问怎么解决？

**Comment by wangweiweinimeng** [comment]
> pip install transformers 后，from transformers import LLaMATokenizer, LLaMAForCausalLM 报错，为什么，或者哪里错了？

请问这个问题后来解决了吗？谢谢

**Comment by qiyuan-chen** [comment]
感谢您的关注。这个问题是由您的网络环境导致的，可以尝试配置VPN来解决。或者尝试在colab中运行。我们注意到很多朋友都在这块出现了问题，后续我们会修改代码使得装包的过程变得更加容易。请保持关注！感谢
